apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hhoz4l637-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hhoz4l637-java-quarkus-gitops